// Minimal SGDK program that plays an MMLisp score through MMLispDRV.
//
// Build layout (see drv/sgdk/README.md):
//   src/main.c          this file
//   src/mmlispdrv.c     the host glue (copy from drv/sgdk/)
//   inc/mmlispdrv.h
//   inc/mmlispdrv_bin.h generated by `node drv/tools/emit-bin.mjs`
//   res/song.res        BIN resource for the MMB (32 KB aligned)
#include <genesis.h>
#include "mmlispdrv.h"
#include "song.h"        // rescomp output for res/song.res; defines `song_mmb`

int main(bool hardReset)
{
    // Bring up the Z80 driver (uploads the image, waits for ready).
    MMLisp_init();

    // Start every track of the score. Track ids come from the compile step:
    //   node drv/tools/mmb-build.mjs mysong.mmlisp res/song.mmb
    // (ab-core.mmlisp compiles to 5 tracks, ids 0..4.)
    for (u8 id = 0; id < 5; id++)
        MMLisp_startTrack(song_mmb, id);

    while (TRUE)
    {
        // The score plays autonomously off the Z80's own 60 Hz interrupt;
        // the 68k is free. React to markers, drive a scene transition, etc.
        // Example: stop everything on START.
        u16 joy = JOY_readJoypad(JOY_1);
        if (joy & BUTTON_START)
        {
            for (u8 id = 0; id < 5; id++)
                MMLisp_stopTrack(id);
        }

        SYS_doVBlankProcess();
    }

    return 0;
}
