// Minimal SGDK program that plays an MMLisp score through MMLispDRV.
//
// Build layout (see drv/sgdk/README.md):
//   src/main.c          this file
//   src/mmlispdrv.c     the host glue (copy from drv/sgdk/)
//   inc/mmlispdrv.h
//   inc/mmlispdrv_bin.h generated by `node drv/tools/emit-bin.mjs`
//   res/song.res        BIN resources for the MMB and the overlay (32 KB aligned):
//                         BIN song_mmb  "song.mmb"      32768
//                         BIN mmlisp_ovl "mmlispdrv_ovl.bin" 32768
#include <genesis.h>
#include "mmlispdrv.h"
#include "song.h"        // rescomp: `song_mmb` and `mmlisp_ovl` (the overlay ROM)

int main(bool hardReset)
{
    // Bring up the Z80 driver: upload the resident image, wait for ready, and
    // publish the overlay ROM bank (the driver loads cold code from it).
    MMLisp_init(mmlisp_ovl);

    // Start every track of the score. Track ids come from the compile step:
    //   node drv/tools/mmb-build.mjs mysong.mmlisp res/song.mmb
    // (ab-core.mmlisp compiles to 5 tracks, ids 0..4.)
    for (u8 id = 0; id < 5; id++)
        MMLisp_startTrack(song_mmb, id);

    while (TRUE)
    {
        // The score plays autonomously off the Z80's own 60 Hz interrupt;
        // the 68k is free. React to markers, drive a scene transition, etc.
        // Example: stop everything on START.
        u16 joy = JOY_readJoypad(JOY_1);
        if (joy & BUTTON_START)
        {
            for (u8 id = 0; id < 5; id++)
                MMLisp_stopTrack(id);
        }

        SYS_doVBlankProcess();
    }

    return 0;
}
