// Minimal SGDK program that plays an MMLisp score through MMLispDRV.
//
// Build layout (see drv/sgdk/README.md):
//   src/main.c          this file
//   src/mmlispdrv.c     the host glue (copy from drv/sgdk/)
//   inc/mmlispdrv.h
//   inc/mmlispdrv_bin.h    generated by `node drv/tools/emit-bin.mjs`
//   res/mmlispdrv_ovl.bin  the overlay blob (copy from drv/sgdk/)
//   res/song.res        BIN resources for the MMB and the overlay (32 KB aligned):
//                         BIN song_mmb   "song.mmb"          32768
//                         BIN mmlisp_ovl "mmlispdrv_ovl.bin" 32768
//
// Controls: A / START = play, B = stop, C = sample the driver's state.
#include <genesis.h>
#include "mmlispdrv.h"
#include "song.h"        // rescomp: `song_mmb` and `mmlisp_ovl` (the overlay ROM)

// Track ids come from the compile step:
//   node drv/tools/mmb-build.mjs mysong.mmlisp res/song.mmb
// (examples/source/demo1.mmlisp compiles to 5 tracks, ids 0..4.)
#define TRACK_COUNT 5

// Driver state, at its published Z80 RAM addresses (docs/driver.md §5/§6.1).
// `head` is 68k-owned and counts commands posted; `tail` is Z80-owned and counts
// commands consumed. `frame` is the driver's own frame counter — it increments
// once per completed frame_step, so it is the direct answer to "is the Z80
// taking its 60 Hz interrupt and running?".
#define MB_HEAD    0x1910
#define MB_TAIL    0x1911
#define MB_TSTAT   0x1912   // 16 per-track status bytes
#define G_INC      0x1950   // u16, per-frame tick increment (8.8) — 0 freezes ALL
                            //      tracks silently: the accumulator never reaches
                            //      one tick, so nothing ever dispatches again
#define G_TS_ACTIVE 0x197E  // u8, a tempo sweep is running (writes G_INC)
#define G_MMB_BANK 0x1926   // u16, the ROM bank the driver reads the score from
#define G_MASTER   0x195C   // u8,  global master level (0..31)
#define G_ES       0x1954   // u16, EVENT_STREAM payload address in the window
#define G_FRAME    0x19D5   // u16
#define TCB_BASE   0x1C58   // 16 track control blocks, 32 bytes each
#define TCB_STRIDE 32
#define T_STATUS   0        // 0 idle, 1 playing, 2 held, 3 suspended
#define T_PC       4        // u16, stream pointer (window address)
#define T_WAIT     0x0E     // u16, ticks until this track's next dispatch

// Sample everything in ONE bus grab, on demand only. Reading Z80 RAM halts the
// Z80, and doing it every frame right after SYS_doVBlankProcess() lands on the
// scanline where the Z80's own vblank interrupt is asserted — the driver then
// misses interrupts and the score stops advancing. Measured during bring-up:
// with a 5-value readout every frame the score froze outright; at once a second
// it played normally. Never poll this on a timer; press C when you want a
// reading.
typedef struct
{
    u8  head;
    u8  tail;
    u16 frame;
    u16 bank;                   // must stay the bank the MMB was linked at
    u8  master;                 // 0 here = everything is attenuated to silence
    u16 es;                     // EVENT_STREAM base, as the driver resolved it
    u16 inc;                    // tick increment; 0 = every track stalls
    u8  tsActive;               // tempo sweep running?
    u16 wait[TRACK_COUNT];      // ticks each track is still waiting
    u8  status[TRACK_COUNT];    // MB_TSTAT: bit7 active, bit6 fading, bits5-0 marker
    u8  tstate[TRACK_COUNT];    // T_STATUS: 0 idle, 1 playing, 2 HELD, 3 suspended.
                                // `status` bit7 stays set for 2 and 3, but only 1
                                // accumulates ticks — a stuck track shows up here.
    u16 pc[TRACK_COUNT];        // per-track stream pointer; must stay inside the
                                // EVENT_STREAM, else the track is decoding junk
} DrvState;

#define z80Read8(off)  (*((vu8*)(Z80_RAM_START + (off))))
#define z80Read16(off) (z80Read8(off) | (z80Read8((off) + 1) << 8))

static void sampleDriver(DrvState* s)
{
    Z80_requestBus(TRUE);
    s->head   = z80Read8(MB_HEAD);
    s->tail   = z80Read8(MB_TAIL);
    s->frame  = z80Read16(G_FRAME);
    s->bank   = z80Read16(G_MMB_BANK);
    s->master = z80Read8(G_MASTER);
    s->es     = z80Read16(G_ES);
    s->inc      = z80Read16(G_INC);
    s->tsActive = z80Read8(G_TS_ACTIVE);
    for (u8 i = 0; i < TRACK_COUNT; i++)
    {
        u16 tcb = TCB_BASE + i * TCB_STRIDE;
        s->status[i] = z80Read8(MB_TSTAT + i);
        s->tstate[i] = z80Read8(tcb + T_STATUS);
        s->pc[i]     = z80Read16(tcb + T_PC);
        s->wait[i]   = z80Read16(tcb + T_WAIT);
    }
    Z80_releaseBus();
}

static void drawHex(u32 value, u16 digits, u16 x, u16 y)
{
    char hex[16];   // intToHex writes up to 8 digits + NUL
    intToHex(value, hex, digits);
    VDP_drawText(hex, x, y);
}

int main(bool hardReset)
{
    // Bring up the Z80 driver: upload the resident image, publish the overlay
    // ROM bank (the driver loads cold code from it), boot, wait for ready.
    MMLisp_init(mmlisp_ovl);

    // NOT READY means the driver never reached its main loop, so the fault is
    // in the upload/reset path, not in the score (README "Confirming it works").
    if (!MMLisp_isReady())
    {
        VDP_drawText("MMLispDRV NOT READY", 2, 2);
        while (TRUE)
            SYS_doVBlankProcess();
    }
    VDP_drawText("MMLispDRV ready", 2, 2);
    VDP_drawText("A/START play  B stop  C stat", 2, 3);
    VDP_drawText("pad:", 2, 5);
    VDP_drawText("ht:", 2, 7);
    VDP_drawText("frm:", 12, 7);
    VDP_drawText("bank:", 24, 7);
    VDP_drawText("mst:", 2, 8);
    VDP_drawText("es:", 10, 8);
    VDP_drawText("inc:", 21, 8);
    // Two samples a second apart: the right-hand pc/wait are the SECOND reading.
    // Identical columns = the track is not advancing at all.
    VDP_drawText("t s st pc   wait  pc2  wait2", 2, 9);

    u16 prev = 0;
    u16 countdown = 0;
    DrvState snap = { 0 };
    u8 starting = TRACK_COUNT;  // TRACK_COUNT = idle; else the next id to start

    while (TRUE)
    {
        // The score plays autonomously off the Z80's own 60 Hz interrupt; the
        // 68k is free. React to markers, drive a scene transition, etc.
        u16 joy = JOY_readJoypad(JOY_1);
        u16 pressed = joy & ~prev;      // edge, not level

        // Input feedback, drawn only when the pad changes — without it there is
        // no way to tell "the press never arrived" from "the driver ignored it".
        if (joy != prev)
            drawHex(joy, 4, 7, 5);
        prev = joy;

        if (pressed & (BUTTON_A | BUTTON_START))
        {
            starting = 0;               // play from the top
            VDP_drawText("PLAY", 2, 17);
        }

        if (pressed & BUTTON_B)
        {
            starting = TRACK_COUNT;
            for (u8 id = 0; id < TRACK_COUNT; id++)
                MMLisp_stopTrack(id);
            VDP_drawText("STOP", 2, 17);
        }

        // C takes TWO samples one second apart and shows both, so a single
        // screenshot answers "is anything still moving?".
        if (pressed & BUTTON_C)
        {
            sampleDriver(&snap);
            countdown = 60;
        }
        if (countdown && --countdown == 0)
        {
            DrvState s;
            sampleDriver(&s);
            drawHex(snap.head,   2,  6, 7);
            drawHex(snap.tail,   2,  9, 7);
            drawHex(s.frame,     4, 17, 7);   // second reading: must have climbed ~60
            drawHex(s.bank,      4, 30, 7);
            drawHex(s.master,    2,  7, 8);
            drawHex(s.es,        4, 14, 8);
            drawHex(s.inc,       4, 26, 8);
            drawHex(s.tsActive,  2, 31, 8);
            for (u8 id = 0; id < TRACK_COUNT; id++)
            {
                drawHex(id,              1,  2, 10 + id);
                drawHex(snap.tstate[id], 1,  4, 10 + id);
                drawHex(snap.status[id], 2,  6, 10 + id);
                drawHex(snap.pc[id],     4,  9, 10 + id);
                drawHex(snap.wait[id],   4, 14, 10 + id);
                drawHex(s.pc[id],        4, 20, 10 + id);
                drawHex(s.wait[id],      4, 25, 10 + id);
            }
        }

        // Start ONE track per frame. Starting a track costs the Z80 three
        // overlay loads plus a full voice load; five in the same frame is well
        // past the ~59,600 cycles a 60 Hz frame gives it, and the opening notes
        // come out ragged. Spread over five frames it is inaudible (83 ms).
        if (starting < TRACK_COUNT)
            MMLisp_startTrack(song_mmb, starting++);

        SYS_doVBlankProcess();
    }

    return 0;
}
