// Build the SHIPPED Z80 image: the one-voice output-centred engine of
// docs/dac-engine-implementation.md R28 §63 — the mixer, the phase decode and
// corrector, the runtime protocol and the pair expander, generated by
// experimental/dac-stream/ and assembled here into the image an SGDK project
// uploads (drv/sgdk/mmlispdrv_bin.h).
//
// `build-engine-ring.mjs` still builds the superseded ring-consuming engine
// (src/engine.z80); its gates and its baseline tool keep it, and nothing ships
// from it any more.
//
// ONE configuration, and the header the 68000 compiles against is read out of
// that configuration and the assembled symbols — never typed twice.
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assemble } from "./z80asm.mjs";
import { buildConfig, PCM1, PCM1_OPS, PCM1_READY_MARK, PCM1_SILENCE, PCM1_OP_LIMIT, pcm1Base,
  EXPANDER_STEPS } from "../experimental/dac-stream/config.mjs";
import { generateSplit } from "../experimental/dac-stream/decode-split.mjs";
import { protocolLayout } from "../experimental/dac-stream/protocol.mjs";
import { FIFO_PAIRS } from "../experimental/dac-stream/pair-host.mjs";

const SGDK_PAIRS_PER_GRAB = 8;

/** The shipped configuration. */
export const PRODUCTION_CFG = {
  voices: 1, complete: true, levels: 15, workTarget: 0.839, correctorBudget: true,
  production: true, signedSource: true,
};

export function buildEngine() {
  const cfg = buildConfig(PRODUCTION_CFG);
  const r = generateSplit(cfg, { stackFill: true, correct: true, proto: true });
  if (!r.ok) throw new Error(`the production image did not place: ${r.stage} ${r.error ?? ""}`);
  const dir = mkdtempSync(join(tmpdir(), "mmlisp-engine-"));
  let built;
  try {
    const path = join(dir, "engine.z80");
    writeFileSync(path, r.gen.text);
    built = assemble(path);
  } finally { rmSync(dir, { recursive: true, force: true }); }
  const bytes = Uint8Array.from(built.bytes);
  // The image reaches the ring's start: code, the level family and the phase
  // table are all RAM the Z80 needs before its first sample.
  if (bytes.length > cfg.ram.ring[0])
    throw new Error(`the image runs into the ring at $${cfg.ram.ring[0].toString(16)}`);
  const L = protocolLayout(cfg.ram.pub[0]);
  const state = pcm1Base(cfg);
  const header = {
    PROTO_VER: 11,                         // the pair transport (R28); 10 was the ring
    CODE_END: built.symbols.get("code_end"),
    // The SGDK host's grab writes EIGHT pairs, always (padded with IDLE), as
    // four movep.l — the same stop the probe host's five move.b copies took
    // (sgdk/mmlispdrv.c). The engine does not care: it reads sixteen a lap.
    FIFO: cfg.ram.fifo[0], FIFO_PAIRS, PAIRS_PER_GRAB: SGDK_PAIRS_PER_GRAB,
    STATE: state, STATE_SIZE: PCM1.size,
    FIFO_LO: state + PCM1.fifoLo,
    READY: state + PCM1.ready, READY_MARK: PCM1_READY_MARK,
    OP_LIMIT: PCM1_OP_LIMIT, OPS: PCM1_OPS,
    LUT_PAGE: cfg.ram.lut[0] >> 8, LEVELS: cfg.levels,
    SILENCE: PCM1_SILENCE,
    CTL_BOOT_GEN: L.control.bootGeneration.offset,
    CTL_PHASE_GEN: L.control.phaseGeneration.offset,
    CTL_COMMAND_COMMIT: L.control.commandCommit.offset,
    CTL_PHASE_COMMIT: L.control.phaseCommit.offset,
    STEPS_PER_LAP: EXPANDER_STEPS, LAP_SAMPLES: cfg.cycleSlots,
    RATE_HZ: cfg.rateHz,
    stamp: cfg.stamp,
  };
  return { bytes, header, cfg, gen: r.gen, placement: r.gen.placement, symbols: built.symbols };
}
