// Build the MMLispDRV Z80 engine images: one per PCM voice count, generated by
// drv/engine/ (gen-stream.mjs) and assembled here. The C header the 68000
// compiles against (sgdk/mmlispdrv_bin.h, tools/emit-bin.mjs) and the JS mirror
// (live/src/engine-images.js, tools/emit-images.mjs) are read out of these
// builds — never typed twice.
//
// The superseded engines are at tags archive/ring-engine and archive/all-z80;
// the one-voice phase-corrected image that shipped before the light images is
// in git history (D10 S2).
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assemble } from "./z80asm.mjs";
import { buildConfig, PCM1_READY_MARK, PCM1_SILENCE, PCM1_OP_LIMIT, PCMN_L, NV_MAX_VOICES } from "../engine/config.mjs";
import { generate, LP_LIGHT_AT } from "../engine/gen-stream.mjs";

/** Pairs in the engine's pair page. */
export const FIFO_PAIRS = 128;

// ── THE LIGHT IMAGES (docs/driver.md §5) ────────────
//
// One image per PCM voice count, chosen by the score's `(def pcm-voices N)`.
// No phase decode, no corrector, no protocol — `generate()` alone — the rung
// levels, no octave step, the loop-capable six-piece edge. The periods are the
// highest the generator places at the 100% work ceiling (the user's choice),
// MEASURED with `npm run light-study`; re-run it after any change to the
// pieces and write what it finds here. The build refuses a period that no
// longer places rather than quietly shipping a slot that overruns.

export const LIGHT_IMAGES = {
  1: { period: 249, lapBlocks: 7 },
  2: { period: 354, lapBlocks: 5 },
  3: { period: 538, lapBlocks: 3 },
};
/** Pairs a second the expander is sized for: the host's wire (design §1.7). */
export const LIGHT_WIRE = 960;
export const LIGHT_WORK_TARGET = 1.0;

export function lightImageConfig(voices) {
  const img = LIGHT_IMAGES[voices];
  if (!img) throw new Error(`no light image for ${voices} voices (1..${NV_MAX_VOICES})`);
  const sampleMaster = img.period * 15;
  const lapSeconds = (img.lapBlocks * 16 * sampleMaster) / 53693175;
  return buildConfig({ voices, complete: true, pairs: true, signedSource: true, production: true,
    loops: true, stepVoices: 0, workTarget: LIGHT_WORK_TARGET, meanTarget: LIGHT_WORK_TARGET,
    sampleMaster, lapBlocks: img.lapBlocks,
    xpSteps: Math.max(8, Math.ceil(LIGHT_WIRE * lapSeconds)) });
}

/**
 * HOW MANY IDLE PAIRS MUST FOLLOW A GENERATION PAIR before the next staged
 * store for the same voice (design §2.3), computed from THIS image's slots.
 *
 * A generation consumed by the expander in slot `a` is seen by the voice's
 * first detection piece in a later slot; the staged bytes it names are read by
 * APPLY (END, WRAP) and, for a start, by START (the source) in later slots
 * still. A store for the same voice consumed strictly between `a` and that
 * last read would be applied by the wrong generation. Inside one slot the
 * pieces run before the expander, so a store consumed IN the reading slot is
 * safe. The answer is the most expander steps that can fall in that window,
 * over every step of the lap and every voice.
 */
function idleAfterGeneration(cfg, sites) {
  const n = cfg.cycleSlots, B = cfg.blockSamples;
  const [pSG, pEG, pAP] = LP_LIGHT_AT[cfg.voices];
  const aSlots = sites.map((x) => x.a);
  const slotsAt = (v, bv) => {
    const out = [];
    for (let s = 0; s < n; s++) if ((((s + cfg.lead - cfg.voiceOffsets[v]) % B) + B) % B === bv) out.push(s);
    return out;
  };
  // The first slot of `list` strictly after absolute slot `after` (unrolled laps).
  const nextAfter = (list, after) => {
    for (let lap = Math.floor(after / n); ; lap++)
      for (const s of list) if (lap * n + s > after) return lap * n + s;
  };
  const stepsBetween = (a, z) => {
    let k = 0;
    for (let lap = Math.floor(a / n); lap * n <= z; lap++)
      for (const s of aSlots) { const t = lap * n + s; if (t > a && t < z) k++; }
    return k;
  };
  let worst = 0;
  for (let v = 0; v < cfg.voices; v++) {
    const sg = slotsAt(v, pSG), eg = slotsAt(v, pEG), ap = slotsAt(v, pAP), st = slotsAt(v, 0);
    for (const a of aSlots) {
      const startApply = nextAfter(ap, nextAfter(sg, a));
      worst = Math.max(worst, stepsBetween(a, nextAfter(st, startApply)));
      worst = Math.max(worst, stepsBetween(a, nextAfter(ap, nextAfter(eg, a))));
    }
  }
  return worst;
}

/** Everything a host, the exporter or a model needs to know about one image. */
export function lightDescriptor(cfg, gen, symbols, bytes) {
  const sites = gen.expander.sites;
  const state = cfg.ram.glob[0] + 0x30;
  return {
    voices: cfg.voices,
    periodCycles: cfg.periodCycles,
    periodMaster: cfg.profile.sampleMaster,
    rateHz: +cfg.rateHz.toFixed(3),
    lapSamples: cfg.cycleSlots,
    stepsPerLap: cfg.xpSteps,
    lead: cfg.lead,
    blockSamples: cfg.blockSamples,
    voiceOffsets: cfg.voiceOffsets,
    lightAt: LP_LIGHT_AT[cfg.voices],
    xpSlots: sites.map((x) => x.a),
    idleAfterGen: idleAfterGeneration(cfg, sites),
    lutPage: cfg.ram.lut[0] >> 8,
    silence: PCM1_SILENCE,
    fifo: cfg.ram.fifo[0],
    fifoPairs: FIFO_PAIRS,
    state,
    opStride: 9,
    opLimit: PCM1_OP_LIMIT,
    fifoLo: state + PCMN_L.fifoLo,
    ready: state + PCMN_L.ready,
    readyMark: PCM1_READY_MARK,
    binSize: bytes.length,
    codeEnd: symbols.get("code_end"),
    stamp: cfg.stamp,
  };
}

/**
 * One light image: `{ bytes, cfg, gen, symbols, descriptor }`.
 * `fault: "mis-cost"` puts one uncosted `nop` in the mix — the gate's TIME
 * negative, nothing else.
 */
export function buildLightImage(voices, { fault = null } = {}) {
  const cfg = lightImageConfig(voices);
  const gen = generate(cfg);
  if (gen.slots.some((s) => s.row.pad < 0) || gen.placement.worst.workPct > 100 * LIGHT_WORK_TARGET)
    throw new Error(`the ${voices}-voice light image no longer places at period ${LIGHT_IMAGES[voices].period}`
      + ` (worst ${gen.placement.worst.workPct}%) — re-run npm run light-study`);
  let text = gen.text;
  if (fault === "mis-cost") {
    text = text.replace(/^mix_one:$/m, "mix_one:\n        nop");
    if (text === gen.text) throw new Error("the mis-cost fault found no mix_one");
  } else if (fault) throw new Error(`unknown image fault ${fault}`);
  const dir = mkdtempSync(join(tmpdir(), "mmlisp-light-"));
  let built;
  try {
    const path = join(dir, "engine.z80");
    writeFileSync(path, text);
    built = assemble(path);
  } finally { rmSync(dir, { recursive: true, force: true }); }
  const bytes = Uint8Array.from(built.bytes);
  if (bytes.length > cfg.ram.lut[1])
    throw new Error(`the ${voices}-voice light image is ${bytes.length} B, past the level pages`);
  return { bytes, cfg, gen, symbols: built.symbols, descriptor: lightDescriptor(cfg, gen, built.symbols, bytes) };
}
