// Assemble the three light engine images and emit what a 68k project links:
//   drv/sgdk/mmlispdrv_bin.h   the images as C arrays, the image table, and the
//                              ABI constants read out of the builds themselves
//
// One image per PCM voice count (docs/driver.md §5);
// the host uploads the one a score's MMB header names. Everything the three
// share — the pair page, the state block, the op layout, the rung pages — is
// identical by construction, and checked here rather than assumed.
//
//   node tools/emit-bin.mjs [--check]
//
// `--check` writes nothing and fails when the committed header is not what
// the images build to now (install-sgdk.mjs and `npm run mirrors` use it).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildLightImage } from "./build-engine.mjs";
import { SGDK_PAIRS_PER_GRAB } from "./pairs-model.mjs";
import { pcmBankStamp } from "../../live/src/mmb.js";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "sgdk", "mmlispdrv_bin.h");
export const PROTO_VER = 12;

export function headerSource() {
  const imgs = [1, 2, 3].map((v) => buildLightImage(v));
  const d0 = imgs[0].descriptor;
  const SHARED = ["fifo", "fifoPairs", "state", "opStride", "opLimit", "fifoLo", "ready", "readyMark",
    "lutPage", "silence", "binSize"];
  for (const { descriptor: d } of imgs)
    for (const k of SHARED)
      if (d[k] !== d0[k]) throw new Error(`emit-bin: pcm${d.voices}'s ${k} is ${d[k]}, pcm1's ${d0[k]} — the images must share the ABI`);
  const hex = (n) => `0x${n.toString(16).toUpperCase()}`;
  const array = (bytes) => {
    const rows = [];
    for (let i = 0; i < bytes.length; i += 16)
      rows.push("    " + [...bytes.slice(i, i + 16)].map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(",") + ",");
    return rows.join("\n");
  };
  const stamps = imgs.map(({ descriptor: d }) => pcmBankStamp(d.rateHz));
  return `// Generated by drv/tools/emit-bin.mjs — DO NOT EDIT BY HAND.
// MMLispDRV Z80 engine images: one per PCM voice count, ${d0.binSize} bytes each,
// uploaded to Z80 RAM at 0x0000 (docs/driver.md §5).
#ifndef MMLISPDRV_BIN_H
#define MMLISPDRV_BIN_H

#include <types.h>

// RATE-STAMPS ${stamps.join(" ")} — the images' DAC rates (tools/rate-mirrors.mjs).
#define MMLISPDRV_PROTO_VER      ${PROTO_VER}
#define MMLISPDRV_BIN_SIZE       ${d0.binSize}

// The pair page (driver.md §6.1): ${d0.fifoPairs} {op, val} pairs the 68000 writes and the
// engine consumes once each, at its expander's own slots.
#define MMLISPDRV_FIFO           ${hex(d0.fifo)}
#define MMLISPDRV_FIFO_PAIRS     ${d0.fifoPairs}
#define MMLISPDRV_PAIRS_PER_GRAB ${SGDK_PAIRS_PER_GRAB}   // what one grab writes, always (IDLE-padded)

// The PCM state block. A pair {op, val} with op < OP_PORT stores val at
// STATE + op; OP_PORT picks the YM port; op >= OP_LIMIT is a YM register.
// Voice v's run of ops (v = 0..2):
#define MMLISPDRV_STATE          ${hex(d0.state)}
#define MMLISPDRV_OP_IDLE        0x0
#define MMLISPDRV_OP_STRIDE      ${d0.opStride}
#define MMLISPDRV_OP_LEVEL(v)    (0x01 + 9 * (v))   // rung page: LUT_PAGE + 0 silence .. + 7 unity
#define MMLISPDRV_OP_SRC_LO(v)   (0x02 + 9 * (v))   // staged start: the blob's window address
#define MMLISPDRV_OP_END_LO(v)   (0x04 + 9 * (v))   // staged END: last byte to play + 1 - 16
#define MMLISPDRV_OP_WRAP_LO(v)  (0x06 + 9 * (v))   // staged WRAP: where the voice goes at END
#define MMLISPDRV_OP_START(v)    (0x08 + 9 * (v))   // a NEW value: source, END, WRAP at the next edges
#define MMLISPDRV_OP_RETARGET(v) (0x09 + 9 * (v))   // a NEW value: END, WRAP at the next edges
#define MMLISPDRV_OP_PORT        0x20
#define MMLISPDRV_OP_LIMIT       ${hex(d0.opLimit)}

// Z80-owned bytes the 68000 reads.
#define MMLISPDRV_FIFO_LO        ${hex(d0.fifoLo)}   // the expander's next pair, as a byte offset into FIFO
#define MMLISPDRV_READY          ${hex(d0.ready)}
#define MMLISPDRV_READY_MARK     ${hex(d0.readyMark)}

#define MMLISPDRV_LUT_PAGE       ${hex(d0.lutPage)}
// Where a parked voice reads: the sample bank's top page must be silence.
#define MMLISPDRV_SILENCE        ${hex(d0.silence)}

${imgs.map(({ bytes, descriptor: d }) => `// pcm${d.voices}: ${d.rateHz.toFixed(2)} Hz, a lap of ${d.lapSamples} samples, ${d.stepsPerLap} expander steps a lap — ${d.stamp}
static const u8 mmlispdrv_pcm${d.voices}[${bytes.length}] = {
${array(bytes)}
};`).join("\n\n")}

typedef struct {
    const u8* bin;
    u16 rateHz;         // rounded: what a sample bank baked for this image is stamped with
    u16 lapSamples;
    u8  voices;
    u8  idleAfterGen;   // IDLE pairs after a START/RETARGET before a staged store for its voice
} MMLispDrvImage;

// Indexed by PCM voice count - 1.
static const MMLispDrvImage MMLISPDRV_IMAGES[3] = {
${imgs.map(({ descriptor: d }) => `    { mmlispdrv_pcm${d.voices}, ${pcmBankStamp(d.rateHz)}, ${d.lapSamples}, ${d.voices}, ${d.idleAfterGen} },`).join("\n")}
};

#endif
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const text = headerSource();
  if (process.argv.includes("--check")) {
    let committed = "";
    try { committed = readFileSync(OUT, "utf8"); } catch { /* missing */ }
    if (committed !== text) {
      console.log("FAIL  sgdk/mmlispdrv_bin.h is not what the images build to now — run node tools/emit-bin.mjs");
      process.exit(1);
    }
    console.log("ok    sgdk/mmlispdrv_bin.h matches the three light images");
  } else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT}`);
  }
}
