// Generate banked engine binaries, browser schedules, and portable rate stamps.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMultibankImage } from './build-multibank.mjs';
import { pcmBankStamp } from '../../live/src/mmb.js';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const voiceCounts = [1, 2];
export function bankedSources() {
  const images = [60, 50].flatMap(frameHz => voiceCounts.map(voices => buildMultibankImage({ voices, frameHz })));
  const descriptors = images.map(({ cfg, gen }) => ({
    multibank: true, frameHz: cfg.machine.region === 'pal' ? 50 : 60,
    masterHz: cfg.machine.masterHz, frameMaster: cfg.machine.frameMaster,
    voices: cfg.voices, rateHz: cfg.rateHz, periodMaster: cfg.periodCycles * 15,
    lapSamples: cfg.cycleSlots, lead: 32, lutPage: 0x13, actions: gen.actions,
  }));
  const count = voiceCounts.length;
  const js = '// GENERATED by drv/tools/emit-banked.mjs.\nconst images=' + JSON.stringify(descriptors)
    + `;\nexport function bankedEngineImage(voices, frameHz=60) { if (voices<1 || voices>${count} || ![50,60].includes(frameHz)) throw new RangeError("unsupported banked PCM profile"); return images[(frameHz===50?${count}:0)+voices-1]; }\n`;
  const arrays = images.map(({ bytes }, i) => `static const u8 mmlispdrv_banked${i+1}[${bytes.length}] = {\n`
    + Array.from({ length: Math.ceil(bytes.length/16) }, (_, row) => '  '
      + [...bytes.slice(row*16, row*16+16)].map(x => '0x'+x.toString(16).padStart(2,'0')).join(',') + ',').join('\n') + '\n};').join('\n');
  const rows = (start) => images.slice(start, start+count).map(({ cfg, gen }, i) =>
    ` {mmlispdrv_banked${start+i+1},${pcmBankStamp(cfg.rateHz)},${cfg.cycleSlots},${cfg.voices},${gen.idleAfterGen}},`).join('\n');
  const header = `// GENERATED by drv/tools/emit-banked.mjs.\n#ifndef MMLISPDRV_BANKED_BIN_H\n#define MMLISPDRV_BANKED_BIN_H\n#include "mmlispdrv_bin.h"\n${arrays}\nstatic const MMLispDrvImage MMLISPDRV_BANKED_IMAGES[${count}] = {\n${rows(0)}\n};\nstatic const MMLispDrvImage MMLISPDRV_BANKED_IMAGES_PAL[${count}] = {\n${rows(count)}\n};\n#endif\n`;
  const rates = `// GENERATED by drv/tools/emit-banked.mjs.\n#ifndef MML_BANKED_RATE_H\n#define MML_BANKED_RATE_H\n#define MML_BANKED_VOICES ${count}\nstatic const unsigned short MML_BANKED_STAMPS[2][${count}] = {\n {${images.slice(0,count).map(x=>pcmBankStamp(x.cfg.rateHz)).join(',')}},\n {${images.slice(count).map(x=>pcmBankStamp(x.cfg.rateHz)).join(',')}}\n};\n#endif\n`;
  return [['live/src/engine-banked-images.js', js], ['drv/sgdk/mmlispdrv_banked_bin.h', header], ['drv/68k/mml_banked_rate.h', rates]];
}
if (process.argv[1] === fileURLToPath(import.meta.url)) for (const [path, source] of bankedSources()) {
  const out = resolve(root, path);
  if (process.argv.includes('--check')) {
    if (readFileSync(out,'utf8') !== source) throw new Error(path+' differs from its generated images');
  } else writeFileSync(out, source);
}
