// Assemble the driver and emit the artifacts an SGDK (or any 68k) project
// links against:
//   drv/sgdk/mmlispdrv.bin       raw Z80 image (for an SGDK BIN resource)
//   drv/sgdk/mmlispdrv_bin.h     the same image as a C array + size macro
//
// The image is position-independent data (uploaded to Z80 RAM at 0x0000), so
// both forms are interchangeable; the .bin suits `BIN` resources, the header
// suits a direct `Z80_loadCustomDriver(mmlispdrv_bin, MMLISPDRV_SIZE)`.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { assemble } from "./z80asm.mjs";
import { generateTables } from "./gen-tables.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "..", "src");
const outDir = join(here, "..", "sgdk");

writeFileSync(join(srcDir, "tables.z80"), generateTables());
const { bytes } = assemble(join(srcDir, "mmlispdrv.z80"));

writeFileSync(join(outDir, "mmlispdrv.bin"), bytes);

const rows = [];
for (let i = 0; i < bytes.length; i += 12) {
  rows.push(
    "    " +
      [...bytes.slice(i, i + 12)].map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ") +
      ",",
  );
}
const header = `// Generated by drv/tools/emit-bin.mjs — DO NOT EDIT BY HAND.
// MMLispDRV M1 Z80 image, ${bytes.length} bytes, uploaded to Z80 RAM at 0x0000.
#ifndef MMLISPDRV_BIN_H
#define MMLISPDRV_BIN_H

#include <types.h>

#define MMLISPDRV_SIZE ${bytes.length}

const u8 mmlispdrv_bin[MMLISPDRV_SIZE] = {
${rows.join("\n")}
};

#endif
`;
writeFileSync(join(outDir, "mmlispdrv_bin.h"), header);

console.log(`sgdk/mmlispdrv.bin + mmlispdrv_bin.h: ${bytes.length} bytes`);
