// Generate the optional banked engine images and browser timing descriptors.
import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildMultibankImage} from './build-multibank.mjs';
import {pcmBankStamp} from '../../live/src/mmb.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
export function bankedSources() {
const images=[1,2].map(voices=>buildMultibankImage({voices,xpSteps:voices===1?55:15}));
const descriptors=images.map(({cfg,gen})=>({multibank:true,voices:cfg.voices,rateHz:cfg.rateHz,periodMaster:cfg.periodCycles*15,lapSamples:80,lead:32,lutPage:0x13,actions:gen.actions}));
const js='// GENERATED by drv/tools/emit-banked.mjs.\nconst images='+JSON.stringify(descriptors)+';\nexport function bankedEngineImage(voices) { if (voices<1 || voices>2) throw new RangeError("banked PCM requires 1–2 voices"); return images[voices-1]; }\n';
const arrays=images.map(({bytes},i)=>`static const u8 mmlispdrv_banked${i+1}[${bytes.length}] = {\n${Array.from({length:Math.ceil(bytes.length/16)},(_,row)=>'  '+[...bytes.slice(row*16,row*16+16)].map(x=>'0x'+x.toString(16).padStart(2,'0')).join(',')+',').join('\n')}\n};`).join('\n');
const header=`// GENERATED by drv/tools/emit-banked.mjs.\n#ifndef MMLISPDRV_BANKED_BIN_H\n#define MMLISPDRV_BANKED_BIN_H\n#include "mmlispdrv_bin.h"\n${arrays}\nstatic const MMLispDrvImage MMLISPDRV_BANKED_IMAGES[2] = {\n${images.map(({cfg,gen},i)=>` {mmlispdrv_banked${i+1},${pcmBankStamp(cfg.rateHz)},80,${cfg.voices},${gen.idleAfterGen}},`).join('\n')}\n};\n#endif\n`;
return [['live/src/engine-banked-images.js',js],['drv/sgdk/mmlispdrv_banked_bin.h',header]];
}
if(process.argv[1] === fileURLToPath(import.meta.url)) for(const [path,source] of bankedSources()){
 const out=resolve(root,path);
 if(process.argv.includes('--check')){if(readFileSync(out,'utf8')!==source)throw new Error(path+' differs from its generated images');}
 else writeFileSync(out,source);
}
