// Generate banked engine binaries, browser schedules, and portable rate stamps.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMultibankImage } from './build-multibank.mjs';
import { engineCode, cByteArray } from './engine-rom.mjs';
import { pcmBankStamp } from '../../live/src/mmb.js';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const voiceCounts = [1, 2, 3];
const palVoiceCounts = [1, 2, 3];
export function bankedSources() {
  const images = [60, 50].flatMap(frameHz => (frameHz===50?palVoiceCounts:voiceCounts).map(voices => buildMultibankImage({ voices, frameHz })));
  const descriptors = images.map(({ cfg, gen }) => ({
    multibank: true, frameHz: cfg.machine.region === 'pal' ? 50 : 60,
    masterHz: cfg.machine.masterHz, frameMaster: cfg.machine.frameMaster,
    voices: cfg.voices, rateHz: cfg.rateHz, periodMaster: cfg.periodCycles * 15,
    lapSamples: cfg.cycleSlots, lead: 32, lutPage: 0x13, actions: gen.actions,
  }));
  const count = voiceCounts.length;
  const js = '// GENERATED by drv/tools/emit-banked.mjs.\nconst images=' + JSON.stringify(descriptors)
    + `;\nexport function bankedEngineImage(voices, frameHz=60) { if (voices<1 || voices>${count} || (frameHz===50 && voices>${palVoiceCounts.length}) || ![50,60].includes(frameHz)) throw new RangeError("unsupported banked PCM profile"); return images[(frameHz===50?${count}:0)+voices-1]; }\n`;
  // PAL changes the bake clock, but the two/three-voice instruction streams
  // are identical. Share exact binaries to avoid duplicate ROM images.
  const unique = [];
  const binIndex = images.map(image => {
    let at = unique.findIndex(other => other.bytes.length === image.bytes.length
      && other.bytes.every((value,i) => value === image.bytes[i]));
    if (at < 0) { at = unique.length; unique.push(image); }
    return at + 1;
  });
  const codes = unique.map(({ bytes, symbols }) => engineCode(bytes, symbols.get('code_end')));
  const arrays = codes.map((code, i) => cByteArray(`mmlispdrv_banked${i+1}`, code)).join('\n');
  const rows = (start) => images.slice(start, start+count).map(({ cfg, gen }, i) =>
    ` {mmlispdrv_banked${binIndex[start+i]},${codes[binIndex[start+i]-1].length},${pcmBankStamp(cfg.rateHz)},${cfg.cycleSlots},${cfg.voices},${gen.idleAfterGen}},`).join('\n');
  const header = `// GENERATED by drv/tools/emit-banked.mjs.\n#ifndef MMLISPDRV_BANKED_BIN_H\n#define MMLISPDRV_BANKED_BIN_H\n#include "mmlispdrv_bin.h"\n${arrays}\nstatic const MMLispDrvImage MMLISPDRV_BANKED_IMAGES[${count}] = {\n${rows(0)}\n};\nstatic const MMLispDrvImage MMLISPDRV_BANKED_IMAGES_PAL[${palVoiceCounts.length}] = {\n${rows(count)}\n};\n#endif\n`;
  const rates = `// GENERATED by drv/tools/emit-banked.mjs.\n#ifndef MML_BANKED_RATE_H\n#define MML_BANKED_RATE_H\n#define MML_BANKED_VOICES ${count}\nstatic const unsigned short MML_BANKED_STAMPS[2][${count}] = {\n {${images.slice(0,count).map(x=>pcmBankStamp(x.cfg.rateHz)).join(',')}},\n {${voiceCounts.map((v,i)=>images[count+i]?pcmBankStamp(images[count+i].cfg.rateHz):0).join(',')}}\n};\n#endif\n`;
  return [['live/src/engine-banked-images.js', js], ['drv/sgdk/mmlispdrv_banked_bin.h', header], ['drv/68k/mml_banked_rate.h', rates]];
}
if (process.argv[1] === fileURLToPath(import.meta.url)) for (const [path, source] of bankedSources()) {
  const out = resolve(root, path);
  if (process.argv.includes('--check')) {
    if (readFileSync(out,'utf8') !== source) throw new Error(path+' differs from its generated images');
  } else writeFileSync(out, source);
}
