// Write live/src/engine-images.js — the light engine images' descriptors, the
// one copy the browser, the exporter and the reference driver read
// (docs/driver.md §5).
//
//   node tools/emit-images.mjs [--check]
//
// Every value is read out of the image as built (tools/build-engine.mjs
// buildLightImage), never typed. `--check` writes nothing and fails when the
// committed file is not what the build makes now — `npm run mirrors` runs it.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildLightImage } from "./build-engine.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "..", "live", "src", "engine-images.js");

export function imagesSource() {
  const rows = [1, 2, 3].map((v) => buildLightImage(v).descriptor);
  const L = [];
  L.push("// GENERATED by drv/tools/emit-images.mjs — do not edit.");
  L.push("//");
  L.push("// The MMLispDRV light engine images, one per PCM voice count, as built:");
  L.push("// the DAC rate, the lap, the expander's step slots, the edge's piece positions,");
  L.push("// the IDLE pairs a host must put after a generation pair, and the addresses");
  L.push("// the host writes (docs/driver.md §5).");
  L.push("");
  L.push("export const ENGINE_IMAGES = Object.freeze({");
  for (const d of rows) L.push(`  ${d.voices}: Object.freeze(${JSON.stringify(d)}),`);
  L.push("});");
  L.push("");
  L.push("/** The image a score with `pcm-voices` N plays on (a score with none uses pcm1's). */");
  L.push("export const engineImage = (pcmVoices) => ENGINE_IMAGES[Math.max(1, Math.min(3, pcmVoices | 0))];");
  L.push("");
  return L.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const text = imagesSource();
  if (process.argv.includes("--check")) {
    let committed = "";
    try { committed = readFileSync(OUT, "utf8"); } catch { /* missing */ }
    if (committed !== text) {
      console.log("FAIL  live/src/engine-images.js is not what the images build to now — run node tools/emit-images.mjs");
      process.exit(1);
    }
    console.log("ok    live/src/engine-images.js matches the three light images");
  } else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT}`);
  }
}
