// Assemble the Z80 engine and emit the artifacts a 68k project links against:
//   drv/sgdk/mmlispdrv.bin      raw Z80 engine image
//   drv/sgdk/mmlispdrv_bin.h    the same image as a C array, plus the interface
//                               constants read out of the assembler's symbols
//
// The image is position-independent data (uploaded to Z80 RAM at 0x0000), so
// both forms are interchangeable; the header is what `mmlispdrv.c` uploads
// (`mmlispdrv_bin`, `MMLISPDRV_BIN_SIZE`).
//
// Post-split there is no overlay blob: the engine is one resident image
// (driver.md §5.2). The 68k's ONE compile-time constant is the published
// header's address — depth, slot size and the ring base are read from that
// header at runtime, so the Z80 owns them (§6.4).
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildEngine } from "./build-engine.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "sgdk");

const { bytes, header, headroom } = buildEngine();

const rows = [];
for (let i = 0; i < bytes.length; i += 12) {
  rows.push(
    "    " +
      [...bytes.slice(i, i + 12)].map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ") +
      ",",
  );
}
const hex = (n) => `0x${n.toString(16).toUpperCase()}`;

writeFileSync(join(outDir, "mmlispdrv.bin"), bytes);
writeFileSync(
  join(outDir, "mmlispdrv_bin.h"),
  `// Generated by drv/tools/emit-bin.mjs — DO NOT EDIT BY HAND.
// MMLispDRV Z80 engine image, ${bytes.length} bytes, uploaded to Z80 RAM at 0x0000.
#ifndef MMLISPDRV_BIN_H
#define MMLISPDRV_BIN_H

#include <types.h>

#define MMLISPDRV_BIN_SIZE ${bytes.length}

// The published header (driver.md §6.4). Its ADDRESS is the only Z80 constant
// the 68k compiles in; the ring's geometry is read from the header itself at
// runtime, so the engine stays the single owner of it. The depth/slot values
// below are for reference and assertions only — never index the ring with them.
#define MMLISPDRV_HDR          ${hex(header.HDR)}
#define MMLISPDRV_PROTO_VER    ${header.PROTO_VER}
#define MMLISPDRV_READY_MARK   ${hex(header.READY_MARK)}
#define MMLISPDRV_RING_DEPTH   ${header.RING_DEPTH}   // reference: read H_DEPTH
#define MMLISPDRV_SLOT_SIZE    ${header.SLOT_SIZE}  // reference: read H_SLOTSH

const u8 mmlispdrv_bin[${bytes.length}] = {
${rows.join("\n")}
};

#endif
`,
);
console.log(
  `sgdk/mmlispdrv.bin + mmlispdrv_bin.h: ${bytes.length} bytes` +
    ` (${headroom} B free below the mix plane) · proto ${header.PROTO_VER}`,
);
