// The driver's constant LUTs, computed from the same JS math the reference
// player uses (driver.md §12.3: the asm never re-derives a table, so JS/asm
// divergence is structurally impossible).
//
// These LUTs used to be baked into the Z80 image (tables.z80 `db`/`dw` data).
// They now live in ROM — a LUT_TABLE MMB section (mmb.md §16) the driver reads
// through the bank window — so they no longer consume the precious 8 KB of Z80
// work RAM. `buildLutBlob()` packs them (for `export-mmb.js` to emit); this
// file's asm output (`tables.z80`) is now just the byte OFFSETS into that blob
// plus a couple of scalars. Layout order is fixed and shared by both.
//
//   FNUM_LUT[12]        u16  A-rooted F-numbers (driver.md §8)
//   PSG_PERIOD_LUT[72]  u16  MIDI 45..116 (driver.md §8)
//   VEL_TL4[16]         u16  velocity → TL attenuation, 1/4-step units
//   VOL_TL4[32]         u16  vol/master → TL offset, 1/4-step units
//   VEL_PSG4[16]        u16  velocity → PSG attenuation, 1/4-step units
//   VOL_PSG4[32]        u16  vol/master → PSG offset, 1/4-step units
//   CARRIER_MASK[8]     u8   algorithm → carrier-op bitmask
//   OP_ADDR_OFF[4]      u8   operator slot → OPN2 register address offset
//   SIN_LUT[256]        u8   sin loop-curve unit (M2 sweeps)
//   PCM_MULT_FRAME[49]  u16  PCM per-frame increment factor C2..C6
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { bpmToTickIncrement } from "../../live/src/mmb.js";
import { buildLutBlob } from "../../live/src/lut-blob.js";

export { buildLutBlob };

// The asm include: byte offsets into the LUT_TABLE blob + scalars. No data.
export function generateTables() {
  const { offsets, size } = buildLutBlob();
  const lines = [
    "; Generated by drv/tools/gen-tables.mjs — DO NOT EDIT BY HAND.",
    "; Byte offsets into the LUT_TABLE MMB section (mmb.md §16). The LUT data",
    "; lives in ROM and is read through the bank window; the driver computes a",
    "; base pointer per label at START_TRACK (= LUT_TABLE window addr + offset).",
    "",
  ];
  for (const [name, off] of Object.entries(offsets)) {
    lines.push(`${name}_OFF equ ${off}`);
  }
  lines.push("");
  lines.push(`LUT_SIZE equ ${size}`);
  lines.push(`DEFAULT_INCREMENT equ ${bpmToTickIncrement(120)} ; 120 BPM, 8.8 ticks/frame`);
  return lines.join("\n") + "\n";
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "tables.z80");
  writeFileSync(out, generateTables());
  const { size } = buildLutBlob();
  console.log(`wrote ${out} (LUT blob ${size} B → ROM/LUT_TABLE)`);
}
