// Generate drv/src/tables.z80 — every constant table the Z80 driver ships,
// printed from the same JS math the reference player uses (driver.md §12.3:
// the asm never re-derives a table, so JS/asm divergence is structurally
// impossible).
//
// Tables (M1 set):
//   FNUM_LUT[12]        u16  A-rooted F-numbers (driver.md §8)
//   PSG_PERIOD_LUT[72]  u16  MIDI 45..116 (driver.md §8)
//   VEL_TL4[16]         u16  velocity → TL attenuation, 1/4-step units
//   VOL_TL4[32]         u16  vol/master → TL offset, 1/4-step units
//   VEL_PSG4[16]        u16  velocity → PSG attenuation, 1/4-step units
//   VOL_PSG4[32]        u16  vol/master → PSG offset, 1/4-step units
//   CARRIER_MASK[8]     u8   algorithm → carrier-op bitmask (bit n = op n+1)
//   OP_ADDR_OFF[4]      u8   operator slot → OPN2 register address offset
//
// The 1/4-step level tables mirror drv-player.js buildLuts(): offsets are
// stored ×4 and the driver rounds the *sum* once — (off4 + 2) >> 2 — matching
// the reference's float-sum-then-quantize within the documented band.
// (Note: driver.md §7 sketches per-term-rounded integer tables; the reference
// implementation supersedes that with the ×4 shared-rounding scheme, and the
// asm follows the reference — the A/B gate is trace equality.)
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  midiToFnumBlock,
  velToTlAtten,
  volToTlOffset,
  velToPsgAtten,
  volToPsgOffset,
  fmCarrierOpsForAlg,
  OP_ADDR_OFFSET,
  PSG_MASTER_CLOCK,
} from "../../live/src/ir-utils.js";
import { bpmToTickIncrement, SIN_LUT } from "../../live/src/mmb.js";

function fnumLut12() {
  // Entries for MIDI 57..68 (A3..G#4): index = (note + 3) mod 12 == 0 at A,
  // block = (note + 3)/12 - 1 == 4 over that span. midiToFnumBlock normalizes
  // every F-number into the 512..1023 window, so this one octave + the block
  // rule reproduces the full-range table bit-exactly for MIDI 9..116.
  const lut = [];
  for (let n = 57; n <= 68; n++) {
    const { fnum, block } = midiToFnumBlock(n);
    if (block !== 4) throw new Error(`unexpected block ${block} at MIDI ${n}`);
    lut.push(fnum);
  }
  return lut;
}

function psgPeriodLut() {
  const lut = [];
  for (let n = 45; n <= 116; n++) {
    const freq = 440 * Math.pow(2, (n - 69) / 12);
    lut.push(
      Math.max(1, Math.min(1023, Math.round(PSG_MASTER_CLOCK / (32 * freq)))),
    );
  }
  return lut;
}

const q4 = (f) => (v) => Math.round(f(v) * 4);
const range = (n, f) => Array.from({ length: n }, (_, i) => f(i));

function carrierMasks() {
  return range(8, (alg) =>
    fmCarrierOpsForAlg(alg).reduce((m, op) => m | (1 << op), 0),
  );
}

function dwBlock(label, comment, values, perLine = 8) {
  const lines = [`${label}: ; ${comment}`];
  for (let i = 0; i < values.length; i += perLine) {
    lines.push(
      "    dw " +
        values
          .slice(i, i + perLine)
          .map((v) => String(v))
          .join(","),
    );
  }
  return lines.join("\n");
}

function dbBlock(label, comment, values) {
  return `${label}: ; ${comment}\n    db ${values.join(",")}`;
}

export function generateTables() {
  const parts = [
    "; Generated by drv/tools/gen-tables.mjs — DO NOT EDIT BY HAND.",
    "; Source of truth: live/src/ir-utils.js + live/src/drv-player.js (buildLuts).",
    "",
    dwBlock(
      "FNUM_LUT",
      "12 x u16, A-rooted F-numbers; index (note+3)%12, block (note+3)/12-1",
      fnumLut12(),
      12,
    ),
    dwBlock(
      "PSG_PERIOD_LUT",
      "72 x u16, SN76489 tone periods for MIDI 45..116; clamp outside",
      psgPeriodLut(),
    ),
    dwBlock(
      "VEL_TL4",
      "16 x u16, vel->TL attenuation in 1/4 TL steps",
      range(16, q4(velToTlAtten)),
    ),
    dwBlock(
      "VOL_TL4",
      "32 x u16, vol/master->TL offset in 1/4 TL steps (shared table)",
      range(32, q4(volToTlOffset)),
    ),
    dwBlock(
      "VEL_PSG4",
      "16 x u16, vel->PSG attenuation in 1/4 att steps",
      range(16, q4(velToPsgAtten)),
    ),
    dwBlock(
      "VOL_PSG4",
      "32 x u16, vol/master->PSG offset in 1/4 att steps (shared table)",
      range(32, q4(volToPsgOffset)),
    ),
    dbBlock(
      "CARRIER_MASK",
      "8 x u8, algorithm -> carrier-op bitmask (bit n = op slot n)",
      carrierMasks(),
    ),
    dbBlock(
      "OP_ADDR_OFF",
      "4 x u8, operator slot -> OPN2 register address offset",
      [...OP_ADDR_OFFSET],
    ),
    dbBlock(
      "SIN_LUT",
      "256 x u8, sin loop-curve unit (1-cos(2pi t/256))/2 * 255 (M2 sweeps)",
      [...SIN_LUT],
    ),
    "",
    `DEFAULT_INCREMENT equ ${bpmToTickIncrement(120)} ; 120 BPM in 8.8 ticks/frame`,
    "",
  ];
  return parts.join("\n\n");
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  const out = join(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "src",
    "tables.z80",
  );
  writeFileSync(out, generateTables());
  console.log(`wrote ${out}`);
}
