// Compile a .mmlisp source to an MMB v0.2 binary on disk, using the same
// live/src toolchain the browser uses. Usage:
//   node mmb-build.mjs <in.mmlisp> <out.mmb>
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, posix, relative, resolve } from "node:path";
import { collectImports, compileMMLisp } from "../../live/src/mmlisp2ir.js";
import { encodeMmb } from "../../live/src/export-mmb.js";
import { loadSamplesForIr } from "./wav.mjs";

/* The sources of every file a score imports, transitively, keyed the way the
 * compiler looks them up (language.md §9.2): the importing file's directory
 * joined with the literal path, as a normalized posix path. The compiler does
 * no I/O — the browser reads the files ahead of it and so does this. A path
 * that does not exist is left out, so the compiler's own E_IMPORT_NOT_FOUND
 * names it. */
export function readImportSources(sourcePath, src = readFileSync(sourcePath, "utf8")) {
  const map = new Map();
  const walk = (filePath, text) => {
    const dir = dirname(filePath).replace(/\\/g, "/");
    for (const p of collectImports(text)) {
      const full = posix.normalize(posix.isAbsolute(p) ? p : posix.join(dir, p));
      if (map.has(full) || !existsSync(full)) continue;
      const t = readFileSync(full, "utf8");
      map.set(full, t);
      walk(full, t);
    }
  };
  walk(sourcePath.replace(/\\/g, "/"), src);
  return map;
}

/* A score's source with the game's effects (a def-se file) imported — on its
 * first line, so the score's own line numbers stand. How a bundle's "se" and
 * `--se` reach every song, without the song naming them. */
export function withSeImport(sourcePath, src, seFile) {
  if (!seFile) return src;
  const rel = relative(dirname(resolve(sourcePath)), resolve(seFile)).split("\\").join("/");
  return `(import ${JSON.stringify(rel)}) ` + src;
}

// `frameHz` picks the video standard the score is baked for (driver.md §3.3):
// 60 for NTSC, 50 for PAL. It has to be given to the COMPILER, not the
// exporter — an `Nf` duration is already ticks by the time the IR exists.
// `seFile` gives the score the game's effects (withSeImport).
export function buildMmb(sourcePath, { frameHz, seFile } = {}) {
  const src = withSeImport(sourcePath, readFileSync(sourcePath, "utf8"), seFile);
  const imports = readImportSources(sourcePath, src);
  const { ir, diagnostics } = compileMMLisp(src, sourcePath, { frameHz, imports });
  const errors = diagnostics.filter((d) => d.severity === "error");
  if (errors.length) {
    throw new Error(
      `compile failed: ${errors.map((e) => e.message).join("; ")}`,
    );
  }
  // PCM songs need the sample blobs (SAMPLE_BANK); load the WAVs the compiler
  // resolved. Non-PCM songs skip this entirely.
  const opts = {};
  const sampleDiags = [];
  if ((ir.metadata?.samples ?? []).length) {
    opts.samples = loadSamplesForIr(ir, sampleDiags);
  }
  const { bytes, sampleBank, pcmEntryIds, diagnostics: exportDiags } = encodeMmb(ir, opts);
  return {
    bytes,
    sampleBank,
    pcmEntryIds,
    ir,
    diagnostics: [...diagnostics, ...sampleDiags, ...exportDiags],
  };
}

/* The score's sound effects (def-se), by number: [{name, prio}]. */
export function seListOf(ir) {
  const out = [];
  for (const t of ir.tracks ?? [])
    if (t.se && !out[t.se.index]) out[t.se.index] = { name: t.se.name, prio: t.se.prio };
  return out;
}

/* The C header a game takes the effects' numbers from — MMLisp_playSe(SE_JUMP).
 * A name is upper-cased with every other character an underscore. */
export function seHeader(list) {
  const lines = [
    "// Generated by MMLisp (tools/bundle.mjs, tools/install-sgdk.mjs) from the",
    "// score's def-se forms: the numbers MMLisp_playSe takes. Do not edit.",
    "#ifndef MMLISP_SE_H",
    "#define MMLISP_SE_H",
    `#define MMLISP_SE_COUNT ${list.length}`,
  ];
  const seen = new Map();
  list.forEach((e, i) => {
    const c = `SE_${e.name.toUpperCase().replace(/[^A-Z0-9]/g, "_")}`;
    if (seen.has(c)) throw new Error(`def-se ${seen.get(c)} and ${e.name} are both ${c} in C`);
    seen.set(c, e.name);
    lines.push(`#define ${c} ${i} // prio ${e.prio}`);
  });
  lines.push("#endif", "");
  return lines.join("\n");
}

/* Point tracks at other channels, in an already-built MMB (TRACK_TABLE: u16
 * count, then 5-byte entries of track id / channel id / flags / offset16).
 * `map` is keyed by TRACK ID. The gates' `.cmds.json` sidecars use it to lay
 * two tracks of one score on one channel, which is how they test starting a
 * TRACK as an effect (mml_start_se); a score's own effects are def-se, which
 * the compiler puts on their channels itself.
 */
export function remapTrackChannels(mmb, map) {
  const u16 = (o) => mmb[o] | (mmb[o + 1] << 8);
  const u32 = (o) => (u16(o) | (u16(o + 2) << 16)) >>> 0;
  const sections = u16(8), header = u16(10);
  const moved = [];
  for (let i = 0; i < sections; i++) {
    const at = header + i * 12;
    if (u16(at) !== 0x0001) continue; // SEC_TRACK_TABLE
    const off = u32(at + 4);
    const count = u16(off);
    for (let k = 0; k < count; k++) {
      const e = off + 2 + k * 5;
      const to = map[mmb[e]];
      if (to == null) continue;
      moved.push({ track: mmb[e], from: mmb[e + 1], to });
      mmb[e + 1] = to;
    }
  }
  return moved;
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  const [inPath, outPath] = process.argv.slice(2);
  if (!inPath || !outPath) {
    console.error("usage: node mmb-build.mjs <in.mmlisp> <out.mmb>");
    process.exit(2);
  }
  const { bytes, sampleBank, diagnostics } = buildMmb(inPath);
  writeFileSync(outPath, bytes);
  console.log(`${outPath}: ${bytes.length} bytes`);
  if (sampleBank && sampleBank.length) {
    // PCM blobs ride a separate sample bank now (plan-se.md), not in the .mmb.
    const smpPath = outPath.replace(/\.mmb$/, "") + ".smp";
    writeFileSync(smpPath, sampleBank);
    console.log(`${smpPath}: ${sampleBank.length} bytes (sample bank)`);
  }
  for (const d of diagnostics) console.warn(`  ${d.severity}: ${d.message}`);
}
