// GENERATED by drv/tools/emit-banked.mjs.
#ifndef MML_BANKED_RATE_H
#define MML_BANKED_RATE_H
#define MML_BANKED_VOICES 3
static const unsigned short MML_BANKED_STAMPS[2][3] = {
 {10112,10112,6653},
 {10019,10019,6593}
};
#endif
