/* GENERATED by tools/gen-c-tables.mjs from live/src/mmb.js — do not edit. */
#ifndef MML_RATE_H
#define MML_RATE_H

#define MML_SPG_NUM 12445
#define MML_SPG_DEN 224
#define MML_SPG_STAMP 3333

/* RATE-STAMP 3333 70 — see tools/rate-mirrors.mjs. */

/* Finished samples the ring runs ahead of the feed: one frame — which is what
 * mml_render_frame() cancels by dispatching a PCM track a frame early — PLUS A
 * QUARTER, which it does not. Production is a burst inside the interrupt and
 * drainage is continuous, so the fill sawtooths a frame deep and a target of
 * exactly one frame puts the trough at zero; the margin is what keeps the ring
 * from running dry, at the price of 4.2 ms of PCM behind the FM. Measured:
 * live/src/mmb.js, PCM_RING_LEAD. It moves with the sample clock, which is why
 * it is generated — it was hand-kept at 255 once, 4.6 frames at 55.6 samples a
 * frame, and the drums played 37 ms late. */
#define MML_PCM_RING_TARGET 70

#endif
