/* GENERATED by tools/gen-c-tables.mjs from live/src/mmb.js — do not edit. */
#ifndef MML_RATE_H
#define MML_RATE_H

#define MML_SPG_NUM 37335
#define MML_SPG_DEN 224
#define MML_SPG_STAMP 10000

#endif
