/* GENERATED by tools/gen-c-tables.mjs from live/src/engine-images.js — do not edit. */
#ifndef MML_RATE_H
#define MML_RATE_H

/* The DAC rate, rounded, of the engine image for 1, 2 and 3 PCM voices: the
 * stamp a sample bank baked for that image carries (mmb.md §10). */
#define MML_PCM_STAMP_1 14376
#define MML_PCM_STAMP_2 10112
#define MML_PCM_STAMP_3 6653

/* RATE-STAMPS 14376 10112 6653 — see tools/rate-mirrors.mjs. */

#endif
