// GENERATED by drv/tools/emit-banked.mjs.
#ifndef MML_BANKED_RATE_H
#define MML_BANKED_RATE_H
#define MML_BANKED_VOICES 2
static const unsigned short MML_BANKED_STAMPS[2][2] = {
 {10112,10112},
 {10019,10019}
};
#endif
